name: Docker CI
on:
  push:
    branches:
      - "master"
    paths:
      - 'build/recorder/**'
      - 'build/webserver/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image (recorder)
        run: docker build -t thirtysix361/twitchrecorder $GITHUB_WORKSPACE/build/recorder/
      - name: Build Docker image (webserver)
        run: docker build -t thirtysix361/twitchrecorder_webserver $GITHUB_WORKSPACE/build/webserver/
      - name: Push Docker image (recorder)
        run: docker push thirtysix361/twitchrecorder:latest
      - name: Push Docker image (webserver)
        run: docker push thirtysix361/twitchrecorder_webserver:latest
